JNG-4501 Release judo meta measure
BlackBeltTechnology/judo-meta-measure pull request #45
Opened 2023-02-28 12:26 UTC by gaborflorian

2023-02-28 14:53 UTC, noherczeg approved these changes

2023-02-28 21:45 UTC, bencegelei requested changes

2023-02-28 21:45 UTC, bencegelei commented on pom.xml
> +				<version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:37 UTC, gaborflorian commented on pom.xml
> +				<version>1.2.11</version>
Requested by Robert

2023-03-01 10:07 UTC, robertcsakany approved these changes

2023-03-01 11:55 UTC, bencegelei approved these changes

2023-03-09 10:24 UTC, merged